image: java:8

#配置缓存路径
cache:
  paths:
    - /root/.m2/repository

stages:
  - test
  - package

before_script:
  - chmod +x ./mvnw

test:
  stage: test
  script:
    - ./mvnw test
    - ./mvnw sonar:sonar -Dsonar.projectKey= $SONAR_PROJECT_KEY -Dsonar.host.url= $SONAR_HOST_URL -Dsonar.login= $SONAR_LOGIN
  #    - ./mvnw sonar:sonar -Dsonar.projectKey=aluminum -Dsonar.host.url=http://192.168.31.53:9000 -Dsonar.login=bed25fb32c7cc5e2a989dbcb056bf359d81a5b06
  only:
    - dev

package:
  stage: package
  script:
    - ./mvnw package
  artifacts:
    paths:
      - ./taget/*.jar
  only:
    - master
