image: java:8

#配置缓存路径
cache:
  paths:
    - /root/.m2/repository

stages:
  - test
  - package

before_script:
  - chmod +x ./mvnw

test:
  stage: test
  script:
    - ./mvnw test
    - ./mvnw sonar:sonar -Dsonar.projectKey=aluminum -Dsonar.host.url=http://192.168.31.53:9000 -Dsonar.login=123d7200c0c547373345434ceb279e4e8c9d9ecfd01
  only:
    - dev

package:
  stage: package
  script:
    - ./mvnw package
  artifacts:
    paths:
      - ./taget/*.jar
  only:
    - master
