image: java:8

#配置缓存路径
cache:
  paths:
    - /root/.m2/repository

stages:
  - test
  - package

before_script:
  - echo $CI_JOB_ID
  - echo $SONAR_HOST_URL
  - echo $SONAR_LOGIN
  - echo $SONAR_PROJECT_KEY
  - chmod +x ./mvnw

test:
  stage: test
  script:
    - ./mvnw test
    - ./mvnw sonar:sonar -Dsonar.projectKey=aluminum -Dsonar.host.url=http://192.168.31.53:9000 -Dsonar.login=aluminum
  only:
    - Han
    - dev

package:
  stage: package
  script:
    - ./mvnw package
  artifacts:
    paths:
      - ./taget/*.jar
  only:
    - master
